services:
    database:
        container_name: postgres
        image: postgres
        networks:
            - mynetwork
        env_file:
            - .env
        volumes:
            - ./:sql/docker-entrypoint-initdb.d
        ports:
            - 5432:5432

    server:
        image: golang
        build: .
        depends_on:
            - database
        networks:
            - mynetwork
        env_file:
            - .env
        ports:
            - 8080:8080

networks:
    mynetwork:
        driver: bridge
