services:
    server:
        build: .
        image: Goland/golang
        depends_on:
            - database
        networks:
            - mynetwork

        env_file:
            - .env
        environment:
            - POSTGRES_HOST=database

        ports:
            - 8080:8080

    database:
        container_name: postgres
        image: postgres
        networks:
            - mynetwork
        env_file:
            - .env

        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432
networks:
    mynetwork:
        driver: bridge
